### ISSUE TITLE
TypeScript 호환 이슈

### ISSUE THREAD

**Issue by sungwon-097** [R22F/ref-client#3]

**Comment by toystory23** [comment]
현재 typescript 버전과 react 버전 충돌 문제 발생 중

**Comment by toystory23** [comment]
tsconfig 파일 내부에서 outFile <=> isolatedModules 간 충돌발생, 
outDir로 인한 이슈 발생([{
	"resource": "/c:/Users/ghldu/Desktop/개발관련/ref-client/tsconfig.json",
	"owner": "typescript",
	"severity": 8,
	"message": "'c:/Users/ghldu/Desktop/개발관련/ref-client/tsconfig.json' 구성 파일에서 입력을 찾을 수 없습니다. 지정된 '포함' 경로는 '[\"src\"]'이고 '제외' 경로는 '[\"./\"]'이었습니다.",
	"source": "ts",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 2
}])
